version: '3.8'
networks:
  hnet:               ### 自建的network
    external: true

services:
  configsvr0:
    container_name: configsvr0
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.5
    ports:
      - 40001:27017

  configsvr1:
    container_name: configsvr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.6
    ports:
      - 40002:27017

