version: '3.8'
networks:
  hnet:               ### 自建的network
    external: true

services:
  mongos:
    container_name: router
    image: mongo
    command: mongos --configdb cfgrs/172.20.1.5:27017,172.20.1.6:27017 --bind_ip 0.0.0.0 --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.11
    ports:
      - 60000:27017

