version: '3.8'
networks:
  hnet:               ### 自建的network
    external: true

services:
  mongos:
    container_name: router
    image: mongo
    command: mongos --configdb cfgrs/172.20.1.5:27017,172.20.1.6:27017 --bind_ip 0.0.0.0 --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.11
    ports:
      - 60000:27017

# sh.addShard("shard0/172.20.1.7:27017")

# sh.addShard("shardrep/172.20.1.8:27017,172.20.1.9:27017")

# sh.addShard("shard1/172.20.1.10:27017")

# sh.addShardTag("shard0", "DBMS1")

# sh.addShardTag("shard1", "DBMS2")

# sh.addShardTag("shardrep", "DBMS12")

# use demo
# sh.enableSharding("demo")

# sh.shardCollection("demo.user_beijing", {"uid": 1})
# sh.addTagRange( 
#   "demo.user_beijing",
#   { "uid" : MinKey },
#   { "uid" : MaxKey },
#   "DBMS1"
# )

# sh.shardCollection("demo.user_hong_kong", {"uid": 1})
# sh.addTagRange(
#   "demo.user_hong_kong",
#   { "uid" : MinKey },
#   { "uid" : MaxKey },
#   "DBMS2"
# )

# sh.shardCollection("demo.article_science", {"aid": 1})
# sh.addTagRange( 
#   "demo.article_science",
#   { "aid" : MinKey },
#   { "aid" : MaxKey },
#   "DBMS12"
# )

# sh.shardCollection("demo.article_tech", {"aid": 1})
# sh.addTagRange(
#   "demo.article_tech",
#   { "aid" : MinKey },
#   { "aid" : MaxKey },
#   "DBMS2"
# )

# sh.shardCollection("demo.read_beijing", {"id": 1})
# sh.addTagRange( 
#   "demo.read_beijing",
#   { "id" : MinKey },
#   { "id" : MaxKey },
#   "DBMS1"
# )

# sh.shardCollection("demo.read_hong_kong", {"id": 1})
# sh.addTagRange(
#   "demo.read_hong_kong",
#   { "id" : MinKey },
#   { "id" : MaxKey },
#   "DBMS2"
# )

# sh.shardCollection("demo.be_read_science", {"brid": 1})
# sh.addTagRange(
#   "demo.be_read_science",
#   { "brid" : MinKey },
#   { "brid" : MaxKey },
#   "DBMS12"
# )

# sh.shardCollection("demo.be_read_tech", {"brid": 1})
# sh.addTagRange(
#   "demo.be_read_tech",
#   { "brid" : MinKey },
#   { "brid" : MaxKey },
#   "DBMS2"
# )

# sh.shardCollection("demo.popular_rank_daily", {"prid": 1})
# sh.addTagRange(
#   "demo.popular_rank_daily",
#   { "prid" : MinKey },
#   { "prid" : MaxKey },
#   "DBMS1"
# )

# sh.shardCollection("demo.popular_rank_weekly", {"prid": 1})
# sh.addTagRange(
#   "demo.popular_rank_weekly",
#   { "prid" : MinKey },
#   { "prid" : MaxKey },
#   "DBMS2"
# )

# sh.shardCollection("demo.popular_rank_monthly", {"prid": 1})
# sh.addTagRange(
#   "demo.popular_rank_monthly",
#   { "prid" : MinKey },
#   { "prid" : MaxKey },
#   "DBMS2"
# )