version: '3.8'
networks:
  hnet:               ### 自建的network
    external: true

services:
  shardsvr00:
    container_name: shardsvr00
    image: mongo
    command: mongod --shardsvr --replSet shard0 --port 27017 
    networks:
      hnet:
        ipv4_address: 172.20.1.7
    ports:
      - 50001:27017

  shardsvr01:
    container_name: shardsvr01
    image: mongo
    command: mongod --shardsvr --replSet shardrep --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.8
    ports:
      - 50002:27017


  shardsvr10:
    container_name: shardsvr10
    image: mongo
    command: mongod --shardsvr --replSet shardrep --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.9
    ports:
      - 50003:27017

  shardsvr11:
    container_name: shardsvr11
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017
    networks:
      hnet:
        ipv4_address: 172.20.1.10
    ports:
      - 50004:27017


# rs.initiate(
#   {
#     _id : "shard0",
#     members: [
#       { _id : 0, host : "172.20.1.7:27017" }
#     ]
#   }
# )

# rs.initiate(
#   {
#     _id : "shardrep",
#     members: [
#       { _id : 0, host : "172.20.1.8:27017" },
#       { _id : 1, host : "172.20.1.9:27017" }
#     ]
#   }
# )

# rs.initiate(
#   {
#     _id : "shard1",
#     members: [
#       { _id : 1, host : "172.20.1.10:27017" }
#     ]
#   }
# )
